# Generated by Django 2.1.1 on 2018-10-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_guestusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestusers',
            name='score',
            field=models.CharField(default='', max_length=200),
        ),
    ]
